# Generated by Django 5.2.6 on 2025-11-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_usuariopermitido_usuariovalidado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioValidado',
        ),
    ]
